apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  namespace: fraud
  labels:
    app: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
              - name: AWS_ACCESS_KEY_ID
                value: "{{ .Values.aws.access }}"
              - name: AWS_SECRET_ACCESS_KEY
                value: "{{ .Values.aws.secret }}"
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"