apiVersion: v1
kind: Service
metadata:
  name: fraud
  namespace: fraud
  labels:
    app: fraud
spec:
  type: ClusterIP
  selector:
    app: fraud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000