image:
  repository: "brusia/fastapi-fraud"
  tag: "0ba067d87528a47be5d5c5e6f8a2e89bedd54a2c"
aws:
  access: "$AWS_ACCESS_KEY_ID"
  secret: "$AWS_SECRET_ACCESS_KEY"
autoscaling:
  minReplicas: 4
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
name: fraud