name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # workflow_dispatch:
  #   paths:
  #     - 'src/**'

env:
  S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
  S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT_URL }}

jobs:
  upload-src:
    name: Upload Source code to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ env.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.S3_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ env.S3_ENDPOINT }}
          SOURCE_DIR: 'src/otus_mlops/scripts/remote'
          DEST_DIR: 'src'
